//go:build !ignore_autogenerated

/**
 * (C) Copyright IBM Corp. 2024.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComposabilityRequest) DeepCopyInto(out *ComposabilityRequest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComposabilityRequest.
func (in *ComposabilityRequest) DeepCopy() *ComposabilityRequest {
	if in == nil {
		return nil
	}
	out := new(ComposabilityRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ComposabilityRequest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComposabilityRequestList) DeepCopyInto(out *ComposabilityRequestList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ComposabilityRequest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComposabilityRequestList.
func (in *ComposabilityRequestList) DeepCopy() *ComposabilityRequestList {
	if in == nil {
		return nil
	}
	out := new(ComposabilityRequestList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ComposabilityRequestList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComposabilityRequestSpec) DeepCopyInto(out *ComposabilityRequestSpec) {
	*out = *in
	in.Resource.DeepCopyInto(&out.Resource)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComposabilityRequestSpec.
func (in *ComposabilityRequestSpec) DeepCopy() *ComposabilityRequestSpec {
	if in == nil {
		return nil
	}
	out := new(ComposabilityRequestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComposabilityRequestStatus) DeepCopyInto(out *ComposabilityRequestStatus) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make(map[string]ScalarResourceStatus, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.ScalarResource.DeepCopyInto(&out.ScalarResource)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComposabilityRequestStatus.
func (in *ComposabilityRequestStatus) DeepCopy() *ComposabilityRequestStatus {
	if in == nil {
		return nil
	}
	out := new(ComposabilityRequestStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComposableResource) DeepCopyInto(out *ComposableResource) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComposableResource.
func (in *ComposableResource) DeepCopy() *ComposableResource {
	if in == nil {
		return nil
	}
	out := new(ComposableResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ComposableResource) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComposableResourceList) DeepCopyInto(out *ComposableResourceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ComposableResource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComposableResourceList.
func (in *ComposableResourceList) DeepCopy() *ComposableResourceList {
	if in == nil {
		return nil
	}
	out := new(ComposableResourceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ComposableResourceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComposableResourceSpec) DeepCopyInto(out *ComposableResourceSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComposableResourceSpec.
func (in *ComposableResourceSpec) DeepCopy() *ComposableResourceSpec {
	if in == nil {
		return nil
	}
	out := new(ComposableResourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComposableResourceStatus) DeepCopyInto(out *ComposableResourceStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComposableResourceStatus.
func (in *ComposableResourceStatus) DeepCopy() *ComposableResourceStatus {
	if in == nil {
		return nil
	}
	out := new(ComposableResourceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeSpec) DeepCopyInto(out *NodeSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeSpec.
func (in *NodeSpec) DeepCopy() *NodeSpec {
	if in == nil {
		return nil
	}
	out := new(NodeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScalarResourceDetails) DeepCopyInto(out *ScalarResourceDetails) {
	*out = *in
	if in.OtherSpec != nil {
		in, out := &in.OtherSpec, &out.OtherSpec
		*out = new(NodeSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScalarResourceDetails.
func (in *ScalarResourceDetails) DeepCopy() *ScalarResourceDetails {
	if in == nil {
		return nil
	}
	out := new(ScalarResourceDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScalarResourceStatus) DeepCopyInto(out *ScalarResourceStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScalarResourceStatus.
func (in *ScalarResourceStatus) DeepCopy() *ScalarResourceStatus {
	if in == nil {
		return nil
	}
	out := new(ScalarResourceStatus)
	in.DeepCopyInto(out)
	return out
}
